# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "dev" , "main"]

env:
  BASE_URL: ${{vars.BASE_URL}}
  QASE_ACCESS_TOKEN: ${{secrets.QASE_ACCESS_TOKEN}}
  QASE_PROJECT_CODE: ${{secrets.QASE_PROJECT_CODE}}

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: |
        pipenv install
        pipenv run playwright install --with-deps
    - name: Lint the code
      run: pipenv run lint
    - name: Run test and send report to qase
      id: test
      run: pipenv run create-all-reports
    - name: Archive results
      if: ${{ success() || steps.test.conclusion == 'failure'}}
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: report.html
        retention-days: 5
